/*
 * This file is part of the openHiTLS project.
 *
 * openHiTLS is licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *     http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
#include "hitls_build.h"
#ifdef HITLS_CRYPTO_PROVIDER
#include "crypt_eal_implprovider.h"
#include "crypt_eal_pkey.h"
#include "crypt_encode_key_impl.h"

/* RSA Key to DER Encoder */
const CRYPT_EAL_Func g_defEalRsaKey2Der[] = {
    {CRYPT_ENCODER_IMPL_NEWCTX, (CRYPT_ENCODER_IMPL_NewCtx)CRYPT_ENCODE_RSA_NewCtx},
    {CRYPT_ENCODER_IMPL_SETPARAM, (CRYPT_ENCODER_IMPL_SetParam)CRYPT_ENCODE_RSA_SetParam},
    {CRYPT_ENCODER_IMPL_GETPARAM, (CRYPT_ENCODER_IMPL_GetParam)CRYPT_ENCODE_RSA_GetParam},
    {CRYPT_ENCODER_IMPL_ENCODE, (CRYPT_ENCODER_IMPL_Encode)CRYPT_ENCODE_RSA_Encode},
    {CRYPT_ENCODER_IMPL_FREEOUTDATA, (CRYPT_ENCODER_IMPL_FreeOutData)CRYPT_ENCODE_RSA_FreeOutData},
    {CRYPT_ENCODER_IMPL_FREECTX, (CRYPT_ENCODER_IMPL_FreeCtx)CRYPT_ENCODE_RSA_FreeCtx},
    CRYPT_EAL_FUNC_END,
};

/* ECC Key to DER Encoder */
const CRYPT_EAL_Func g_defEalEccKey2Der[] = {
    {CRYPT_ENCODER_IMPL_NEWCTX, (CRYPT_ENCODER_IMPL_NewCtx)CRYPT_ENCODE_ECC_NewCtx},
    {CRYPT_ENCODER_IMPL_SETPARAM, (CRYPT_ENCODER_IMPL_SetParam)CRYPT_ENCODE_ECC_SetParam},
    {CRYPT_ENCODER_IMPL_GETPARAM, (CRYPT_ENCODER_IMPL_GetParam)CRYPT_ENCODE_ECC_GetParam},
    {CRYPT_ENCODER_IMPL_ENCODE, (CRYPT_ENCODER_IMPL_Encode)CRYPT_ENCODE_ECC_Encode},
    {CRYPT_ENCODER_IMPL_FREEOUTDATA, (CRYPT_ENCODER_IMPL_FreeOutData)CRYPT_ENCODE_ECC_FreeOutData},
    {CRYPT_ENCODER_IMPL_FREECTX, (CRYPT_ENCODER_IMPL_FreeCtx)CRYPT_ENCODE_ECC_FreeCtx},
    CRYPT_EAL_FUNC_END,
};

/* Generic Key to DER Encoder */
const CRYPT_EAL_Func g_defEalKey2Der[] = {
    {CRYPT_ENCODER_IMPL_NEWCTX, (CRYPT_ENCODER_IMPL_NewCtx)CRYPT_ENCODE_KEY2DER_NewCtx},
    {CRYPT_ENCODER_IMPL_SETPARAM, (CRYPT_ENCODER_IMPL_SetParam)CRYPT_ENCODE_KEY2DER_SetParam},
    {CRYPT_ENCODER_IMPL_GETPARAM, (CRYPT_ENCODER_IMPL_GetParam)CRYPT_ENCODE_KEY2DER_GetParam},
    {CRYPT_ENCODER_IMPL_ENCODE, (CRYPT_ENCODER_IMPL_Encode)CRYPT_ENCODE_KEY2DER_Encode},
    {CRYPT_ENCODER_IMPL_FREEOUTDATA, (CRYPT_ENCODER_IMPL_FreeOutData)CRYPT_ENCODE_KEY2DER_FreeOutData},
    {CRYPT_ENCODER_IMPL_FREECTX, (CRYPT_ENCODER_IMPL_FreeCtx)CRYPT_ENCODE_KEY2DER_FreeCtx},
    CRYPT_EAL_FUNC_END,
};

/* DER to PEM Encoder */
const CRYPT_EAL_Func g_defEalDer2Pem[] = {
    {CRYPT_ENCODER_IMPL_NEWCTX, (CRYPT_ENCODER_IMPL_NewCtx)CRYPT_ENCODE_DER2PEM_NewCtx},
    {CRYPT_ENCODER_IMPL_SETPARAM, (CRYPT_ENCODER_IMPL_SetParam)CRYPT_ENCODE_DER2PEM_SetParam},
    {CRYPT_ENCODER_IMPL_GETPARAM, (CRYPT_ENCODER_IMPL_GetParam)CRYPT_ENCODE_DER2PEM_GetParam},
    {CRYPT_ENCODER_IMPL_ENCODE, (CRYPT_ENCODER_IMPL_Encode)CRYPT_ENCODE_DER2PEM_Encode},
    {CRYPT_ENCODER_IMPL_FREEOUTDATA, (CRYPT_ENCODER_IMPL_FreeOutData)CRYPT_ENCODE_DER2PEM_FreeOutData},
    {CRYPT_ENCODER_IMPL_FREECTX, (CRYPT_ENCODER_IMPL_FreeCtx)CRYPT_ENCODE_DER2PEM_FreeCtx},
    CRYPT_EAL_FUNC_END,
};

#endif /* HITLS_CRYPTO_PROVIDER */